import { Platform, StyleSheet } from 'react-native';

export const PAPER = {
  paper: '#f3e2a8',
  paperDeep: '#e6ce86',
  slip: '#efe4b4',
  ink: '#110c08',
  inkSoft: '#4a3724',
  tabloid: '#c70f2b',
  pitch: '#04110c',
  flood: '#e4c15a',
  slug: '#7dffef',
};

const SERIF = Platform.OS === 'ios' ? 'Times New Roman' : 'serif';
const MONO = Platform.OS === 'ios' ? 'Courier New' : 'monospace';

export const paperStyles = StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: PAPER.pitch,
  },
  headerBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingTop: 4,
    paddingBottom: 8,
    gap: 10,
  },
  headerTitle: {
    color: PAPER.paper,
    fontWeight: '800',
    fontSize: 12,
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  sheet: {
    marginHorizontal: 10,
    marginBottom: 28,
    backgroundColor: PAPER.paper,
    borderWidth: 1,
    borderColor: 'rgba(17,12,8,0.55)',
    overflow: 'hidden',
  },
  masthead: {
    backgroundColor: PAPER.tabloid,
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 10,
  },
  kickerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  kickerSlug: {
    color: PAPER.slug,
    fontSize: 10,
    letterSpacing: 2,
    textTransform: 'uppercase',
    fontWeight: '800',
  },
  kickerMuted: {
    color: 'rgba(243,226,168,0.72)',
    fontSize: 10,
    letterSpacing: 1.4,
    textTransform: 'uppercase',
  },
  title: {
    color: PAPER.paper,
    fontSize: 34,
    lineHeight: 36,
    fontWeight: '900',
    letterSpacing: 1,
    marginTop: 6,
    fontFamily: SERIF,
  },
  dateline: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderBottomWidth: 4,
    borderBottomColor: PAPER.ink,
    backgroundColor: PAPER.paperDeep,
  },
  datelineText: {
    color: PAPER.ink,
    fontSize: 10,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    fontWeight: '700',
    flexShrink: 1,
  },
  sectionTab: {
    minHeight: 44,
    paddingHorizontal: 14,
    justifyContent: 'center',
    borderRightWidth: 1,
    borderRightColor: 'rgba(17,12,8,0.18)',
    backgroundColor: PAPER.paper,
  },
  sectionTabActive: {
    backgroundColor: PAPER.ink,
  },
  sectionTabText: {
    color: PAPER.ink,
    fontSize: 11,
    letterSpacing: 1.4,
    textTransform: 'uppercase',
    fontWeight: '800',
  },
  sectionTabTextActive: {
    color: PAPER.paper,
  },
  desk: {
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 20,
  },
  windowLine: {
    backgroundColor: PAPER.ink,
    color: PAPER.paper,
    fontSize: 11,
    letterSpacing: 1.6,
    textTransform: 'uppercase',
    fontWeight: '800',
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 12,
  },
  deadline: {
    backgroundColor: PAPER.tabloid,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  deadlineLabel: {
    color: PAPER.paper,
    fontSize: 10,
    letterSpacing: 2,
    fontWeight: '900',
  },
  deadlineClock: {
    color: PAPER.paper,
    fontSize: 20,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },
  filterRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 12,
  },
  filterChip: {
    borderWidth: 1,
    borderColor: PAPER.ink,
    minHeight: 36,
    paddingHorizontal: 10,
    justifyContent: 'center',
  },
  filterChipActive: {
    backgroundColor: PAPER.ink,
  },
  filterChipText: {
    color: PAPER.ink,
    fontSize: 10,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    fontWeight: '800',
  },
  filterChipTextActive: {
    color: PAPER.paper,
  },
  search: {
    borderWidth: 1,
    borderColor: PAPER.ink,
    minHeight: 36,
    paddingHorizontal: 10,
    color: PAPER.ink,
    fontSize: 13,
    flexGrow: 1,
    minWidth: 140,
  },
  sectionHead: {
    fontSize: 11,
    letterSpacing: 2,
    textTransform: 'uppercase',
    color: PAPER.ink,
    fontWeight: '800',
    marginBottom: 8,
  },
  tapeRow: {
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(17,12,8,0.18)',
    paddingVertical: 10,
    paddingHorizontal: 4,
  },
  tapeRowActive: {
    backgroundColor: 'rgba(211,18,42,0.08)',
  },
  tapeMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 4,
  },
  tapeTime: {
    fontFamily: MONO,
    fontSize: 11,
    color: PAPER.ink,
  },
  tapeTitle: {
    color: PAPER.ink,
    fontSize: 14,
    fontWeight: '700',
  },
  stamp: {
    alignSelf: 'flex-start',
    borderWidth: 2,
    paddingHorizontal: 6,
    paddingVertical: 2,
    transform: [{ rotate: '-2deg' }],
  },
  stampText: {
    fontFamily: MONO,
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 1.4,
  },
  card: {
    backgroundColor: PAPER.slip,
    borderWidth: 2,
    borderColor: PAPER.ink,
    padding: 14,
    marginBottom: 12,
  },
  cardTitle: {
    color: PAPER.ink,
    fontSize: 22,
    lineHeight: 26,
    fontWeight: '800',
    marginTop: 8,
    fontFamily: SERIF,
  },
  excerpt: {
    color: PAPER.inkSoft,
    fontSize: 14,
    lineHeight: 20,
    marginTop: 8,
  },
  markRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 10,
  },
  markImage: {
    width: 44,
    height: 44,
    borderWidth: 1,
    borderColor: PAPER.ink,
    backgroundColor: '#efe0a4',
  },
  markFallback: {
    width: 44,
    height: 44,
    borderWidth: 1,
    borderColor: PAPER.ink,
    backgroundColor: '#efe0a4',
    alignItems: 'center',
    justifyContent: 'center',
  },
  markFallbackText: {
    color: PAPER.ink,
    fontWeight: '900',
    fontSize: 12,
  },
  markName: {
    color: PAPER.ink,
    fontWeight: '800',
    fontSize: 14,
    flex: 1,
  },
  metaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 10,
  },
  metaLabel: {
    color: PAPER.inkSoft,
    fontSize: 9,
    letterSpacing: 1.4,
    textTransform: 'uppercase',
    fontWeight: '800',
  },
  metaValue: {
    color: PAPER.ink,
    fontSize: 13,
    fontWeight: '700',
    marginTop: 2,
  },
  countries: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 10,
  },
  countryChip: {
    borderWidth: 1,
    borderColor: PAPER.ink,
    paddingHorizontal: 6,
    paddingVertical: 3,
  },
  countryText: {
    color: PAPER.ink,
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1,
  },
  trophy: {
    width: 72,
    height: 72,
    marginTop: 8,
  },
  trophyLarge: {
    width: 120,
    height: 120,
    marginTop: 10,
    alignSelf: 'center',
  },
  winner: {
    color: PAPER.ink,
    fontWeight: '800',
    marginTop: 8,
  },
  detailTitle: {
    color: PAPER.ink,
    fontSize: 24,
    lineHeight: 28,
    fontWeight: '800',
    marginTop: 8,
    fontFamily: SERIF,
  },
  empty: {
    color: PAPER.inkSoft,
    fontSize: 14,
    fontStyle: 'italic',
    paddingVertical: 12,
  },
  loading: {
    color: PAPER.inkSoft,
    fontSize: 14,
    paddingVertical: 24,
    textAlign: 'center',
  },
  link: {
    color: PAPER.tabloid,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    marginRight: 14,
    marginTop: 10,
  },
  boardButton: {
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(17,12,8,0.18)',
    paddingVertical: 10,
  },
  boardStrong: {
    color: PAPER.ink,
    fontWeight: '800',
    fontSize: 13,
  },
  boardSpan: {
    color: PAPER.inkSoft,
    fontSize: 11,
    marginTop: 2,
  },
  phaseBlock: {
    marginTop: 12,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: 'rgba(17,12,8,0.18)',
  },
  phaseTitle: {
    color: PAPER.ink,
    fontSize: 12,
    letterSpacing: 1.4,
    textTransform: 'uppercase',
    fontWeight: '800',
    marginBottom: 6,
  },
  matchLine: {
    color: PAPER.ink,
    fontSize: 13,
    marginTop: 4,
  },
  worldGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  worldCard: {
    width: '47%',
    minHeight: 140,
    borderWidth: 2,
    borderColor: PAPER.ink,
    backgroundColor: PAPER.slip,
    padding: 12,
  },
  worldName: {
    color: PAPER.ink,
    fontSize: 20,
    fontWeight: '800',
    marginTop: 10,
    fontFamily: SERIF,
  },
  worldKicker: {
    color: PAPER.inkSoft,
    fontSize: 11,
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginTop: 4,
  },
  worldCount: {
    color: PAPER.ink,
    fontSize: 12,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    fontWeight: '800',
    marginTop: 10,
  },
  worldBack: {
    borderWidth: 1,
    borderColor: PAPER.paper,
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginLeft: 'auto',
  },
  worldBackText: {
    color: PAPER.paper,
    fontSize: 10,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    fontWeight: '800',
  },
  worldCountryLabel: {
    color: PAPER.ink,
    fontSize: 11,
    letterSpacing: 1.4,
    textTransform: 'uppercase',
    fontWeight: '800',
    marginBottom: 6,
  },
  worldCountryChips: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 12,
  },
  worldCountryChip: {
    borderWidth: 1,
    borderColor: PAPER.ink,
    backgroundColor: PAPER.slip,
    paddingHorizontal: 9,
    paddingVertical: 6,
  },
  worldCountryChipActive: {
    backgroundColor: PAPER.ink,
  },
  worldCountryChipText: {
    color: PAPER.ink,
    fontSize: 12,
    fontWeight: '700',
  },
  worldCountryChipTextActive: {
    color: PAPER.paper,
  },
  worldHint: {
    color: PAPER.inkSoft,
    fontSize: 12,
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  routeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginVertical: 10,
  },
  clubMark: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  clubSide: {
    fontSize: 9,
    letterSpacing: 1.6,
    textTransform: 'uppercase',
    color: PAPER.inkSoft,
    fontWeight: '800',
  },
  arrow: {
    color: PAPER.ink,
    fontSize: 18,
    fontWeight: '900',
  },
  timelineItem: {
    borderLeftWidth: 2,
    borderLeftColor: PAPER.ink,
    paddingLeft: 10,
    marginTop: 10,
  },
  quoteQ: {
    color: PAPER.ink,
    fontWeight: '800',
    fontSize: 13,
  },
  quoteA: {
    color: PAPER.inkSoft,
    fontSize: 13,
    marginTop: 4,
  },
  front: {
    flexDirection: 'column',
  },
  splash: {
    backgroundColor: '#1a140c',
    minHeight: 420,
  },
  splashMedia: {
    height: 420,
    overflow: 'hidden',
    backgroundColor: '#2a2218',
  },
  splashImage: {
    width: '100%',
    height: '100%',
  },
  splashCopy: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 20,
    backgroundColor: PAPER.paper,
  },
  splashHeadline: {
    color: PAPER.ink,
    fontSize: 32,
    lineHeight: 32,
    fontWeight: '900',
    textTransform: 'uppercase',
    fontFamily: SERIF,
  },
  splashDek: {
    color: PAPER.ink,
    fontSize: 16,
    lineHeight: 22,
    marginTop: 10,
  },
  splashMeta: {
    color: PAPER.inkSoft,
    fontSize: 11,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginTop: 10,
    fontWeight: '700',
  },
  inkStamp: {
    position: 'absolute',
    top: 18,
    left: 14,
    borderWidth: 3,
    borderColor: PAPER.tabloid,
    backgroundColor: PAPER.paper,
    paddingHorizontal: 10,
    paddingVertical: 6,
    transform: [{ rotate: '-11deg' }],
    zIndex: 3,
  },
  inkStampText: {
    color: PAPER.tabloid,
    fontSize: 12,
    letterSpacing: 1.8,
    textTransform: 'uppercase',
    fontWeight: '900',
  },
  feeStamp: {
    position: 'absolute',
    right: 16,
    bottom: 28,
    width: 88,
    height: 88,
    borderRadius: 44,
    borderWidth: 3,
    borderColor: PAPER.tabloid,
    backgroundColor: PAPER.paper,
    alignItems: 'center',
    justifyContent: 'center',
    transform: [{ rotate: '-11deg' }],
    zIndex: 3,
  },
  feeStampText: {
    color: PAPER.tabloid,
    fontSize: 12,
    fontWeight: '900',
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  rail: {
    borderTopWidth: 4,
    borderTopColor: PAPER.ink,
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 16,
  },
  brief: {
    flexDirection: 'row',
    gap: 10,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(17,12,8,0.18)',
  },
  briefThumb: {
    width: 72,
    height: 72,
    backgroundColor: '#2a2218',
  },
  briefKicker: {
    color: PAPER.tabloid,
    fontSize: 10,
    letterSpacing: 1.6,
    textTransform: 'uppercase',
    fontWeight: '800',
  },
  briefTitle: {
    color: PAPER.ink,
    fontSize: 16,
    fontWeight: '800',
    marginTop: 4,
    fontFamily: SERIF,
  },
});
