USE eafc_platform;

CREATE TABLE IF NOT EXISTS teams (
  id VARCHAR(36) PRIMARY KEY DEFAULT (UUID()),
  club_name VARCHAR(255) NOT NULL,
  creation_date DATE NOT NULL DEFAULT (CURDATE()),
  country VARCHAR(100) NULL,
  country_code VARCHAR(10) NULL,
  owner_id VARCHAR(36) NOT NULL,
  avatar VARCHAR(500) NULL,
  bio TEXT NULL,
  followers_count INT DEFAULT 0,
  likes_count INT DEFAULT 0,
  wins INT DEFAULT 0,
  draws INT DEFAULT 0,
  losses INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS team_players (
  id VARCHAR(36) PRIMARY KEY DEFAULT (UUID()),
  team_id VARCHAR(36) NOT NULL,
  user_id VARCHAR(36) NOT NULL,
  position VARCHAR(10) NULL COMMENT 'GK,CB,RB,LB,CM,CAM,CDM,RW,LW,ST',
  jersey_number TINYINT NULL,
  role ENUM('owner','captain','player','sub') DEFAULT 'player',
  joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_team_player (team_id, user_id),
  FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS formations (
  id VARCHAR(36) PRIMARY KEY DEFAULT (UUID()),
  team_id VARCHAR(36) NOT NULL,
  name VARCHAR(20) NOT NULL COMMENT '4-3-3,4-4-2,3-5-2,4-2-3-1',
  is_active TINYINT(1) DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS player_positions (
  id VARCHAR(36) PRIMARY KEY DEFAULT (UUID()),
  formation_id VARCHAR(36) NOT NULL,
  user_id VARCHAR(36) NOT NULL,
  position_code VARCHAR(10) NOT NULL COMMENT 'GK,CB,RB,LB,CM,CAM,CDM,RW,LW,ST',
  x_coord DECIMAL(5,2) NULL COMMENT 'Percentage 0-100',
  y_coord DECIMAL(5,2) NULL COMMENT 'Percentage 0-100',
  FOREIGN KEY (formation_id) REFERENCES formations(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS team_user_count (
  user_id VARCHAR(36) PRIMARY KEY,
  team_count TINYINT DEFAULT 0,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
