/** Auto-generated by scripts/generate-locale-registry.mjs — do not edit by hand. */
import ar_commonPages from "./packs/ar.commonPages.json";
import ar_competitionFlow from "./packs/ar.competitionFlow.json";
import ar_matchFlow from "./packs/ar.matchFlow.json";
import ar_tournamentDetail from "./packs/ar.tournamentDetail.json";
import de_commonPages from "./packs/de.commonPages.json";
import de_competitionFlow from "./packs/de.competitionFlow.json";
import de_matchFlow from "./packs/de.matchFlow.json";
import de_tournamentDetail from "./packs/de.tournamentDetail.json";
import es_commonPages from "./packs/es.commonPages.json";
import es_competitionFlow from "./packs/es.competitionFlow.json";
import es_matchFlow from "./packs/es.matchFlow.json";
import es_tournamentDetail from "./packs/es.tournamentDetail.json";
import it_commonPages from "./packs/it.commonPages.json";
import it_competitionFlow from "./packs/it.competitionFlow.json";
import it_matchFlow from "./packs/it.matchFlow.json";
import it_tournamentDetail from "./packs/it.tournamentDetail.json";
import ja_commonPages from "./packs/ja.commonPages.json";
import ja_competitionFlow from "./packs/ja.competitionFlow.json";
import ja_matchFlow from "./packs/ja.matchFlow.json";
import ja_tournamentDetail from "./packs/ja.tournamentDetail.json";
import ko_commonPages from "./packs/ko.commonPages.json";
import ko_competitionFlow from "./packs/ko.competitionFlow.json";
import ko_matchFlow from "./packs/ko.matchFlow.json";
import ko_tournamentDetail from "./packs/ko.tournamentDetail.json";
import nl_commonPages from "./packs/nl.commonPages.json";
import nl_competitionFlow from "./packs/nl.competitionFlow.json";
import nl_matchFlow from "./packs/nl.matchFlow.json";
import nl_tournamentDetail from "./packs/nl.tournamentDetail.json";
import pl_commonPages from "./packs/pl.commonPages.json";
import pl_competitionFlow from "./packs/pl.competitionFlow.json";
import pl_matchFlow from "./packs/pl.matchFlow.json";
import pl_tournamentDetail from "./packs/pl.tournamentDetail.json";
import pt_commonPages from "./packs/pt.commonPages.json";
import pt_competitionFlow from "./packs/pt.competitionFlow.json";
import pt_matchFlow from "./packs/pt.matchFlow.json";
import pt_tournamentDetail from "./packs/pt.tournamentDetail.json";
import ru_commonPages from "./packs/ru.commonPages.json";
import ru_competitionFlow from "./packs/ru.competitionFlow.json";
import ru_matchFlow from "./packs/ru.matchFlow.json";
import ru_tournamentDetail from "./packs/ru.tournamentDetail.json";
import tr_commonPages from "./packs/tr.commonPages.json";
import tr_competitionFlow from "./packs/tr.competitionFlow.json";
import tr_matchFlow from "./packs/tr.matchFlow.json";
import tr_tournamentDetail from "./packs/tr.tournamentDetail.json";
import zh_commonPages from "./packs/zh.commonPages.json";
import zh_competitionFlow from "./packs/zh.competitionFlow.json";
import zh_matchFlow from "./packs/zh.matchFlow.json";
import zh_tournamentDetail from "./packs/zh.tournamentDetail.json";

export const SECTION_PACKS = {
  ar: {
    commonPages: ar_commonPages,
    competitionFlow: ar_competitionFlow,
    matchFlow: ar_matchFlow,
    tournamentDetail: ar_tournamentDetail,
  },
  de: {
    commonPages: de_commonPages,
    competitionFlow: de_competitionFlow,
    matchFlow: de_matchFlow,
    tournamentDetail: de_tournamentDetail,
  },
  es: {
    commonPages: es_commonPages,
    competitionFlow: es_competitionFlow,
    matchFlow: es_matchFlow,
    tournamentDetail: es_tournamentDetail,
  },
  it: {
    commonPages: it_commonPages,
    competitionFlow: it_competitionFlow,
    matchFlow: it_matchFlow,
    tournamentDetail: it_tournamentDetail,
  },
  ja: {
    commonPages: ja_commonPages,
    competitionFlow: ja_competitionFlow,
    matchFlow: ja_matchFlow,
    tournamentDetail: ja_tournamentDetail,
  },
  ko: {
    commonPages: ko_commonPages,
    competitionFlow: ko_competitionFlow,
    matchFlow: ko_matchFlow,
    tournamentDetail: ko_tournamentDetail,
  },
  nl: {
    commonPages: nl_commonPages,
    competitionFlow: nl_competitionFlow,
    matchFlow: nl_matchFlow,
    tournamentDetail: nl_tournamentDetail,
  },
  pl: {
    commonPages: pl_commonPages,
    competitionFlow: pl_competitionFlow,
    matchFlow: pl_matchFlow,
    tournamentDetail: pl_tournamentDetail,
  },
  pt: {
    commonPages: pt_commonPages,
    competitionFlow: pt_competitionFlow,
    matchFlow: pt_matchFlow,
    tournamentDetail: pt_tournamentDetail,
  },
  ru: {
    commonPages: ru_commonPages,
    competitionFlow: ru_competitionFlow,
    matchFlow: ru_matchFlow,
    tournamentDetail: ru_tournamentDetail,
  },
  tr: {
    commonPages: tr_commonPages,
    competitionFlow: tr_competitionFlow,
    matchFlow: tr_matchFlow,
    tournamentDetail: tr_tournamentDetail,
  },
  zh: {
    commonPages: zh_commonPages,
    competitionFlow: zh_competitionFlow,
    matchFlow: zh_matchFlow,
    tournamentDetail: zh_tournamentDetail,
  },
};
